// A card's name, used to find the monster that drops it.
//
// Thirty-nine cards carry a name with no word in common with the monster they
// come off: a Zealotus Card drops from Zherlthsh, an Evil Nymph Card from
// Wicked Nymph, a Mi Gao Card from Increase Soil. The site's search matches
// words against the monster's name, so typing the card's name found nothing.
//
// The claim is narrow and comes from our own monster_drops table: the card
// with this name drops from this monster. It is deliberately not "the monster
// is also called this" -- Baphomet Jr. Card drops from Baphomet, and those are
// two different creatures.
//
// Generated by scripts/build-card-name-aliases.mjs; the rules that keep an
// ambiguous pair out are documented there.

import file from '@/data/card-name-aliases.json';

export interface CardNameAlias {
  alias: string;
  monster: number;
  monsterName: string;
  card: number;
  cardName: string;
}

const data = (file as unknown as { aliases: CardNameAlias[] }).aliases;

function squash(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]/g, '');
}

/**
 * Monster ids whose dropped card carries this name.
 *
 * Matched loosely in both directions so "zealotus card" and "zealotus" both
 * land, but never on a fragment: a two-character query would otherwise match
 * half the table.
 */
export function cardNameMonsterIds(query: string): number[] {
  const q = squash(query);
  if (q.length < 3) return [];
  const out = new Set<number>();
  for (const entry of data) {
    const alias = squash(entry.alias);
    if (q.includes(alias) || alias.includes(q)) out.add(entry.monster);
  }
  return [...out];
}

/** The cards a monster drops that are named after something else. */
export function cardNamesFor(monsterId: number): CardNameAlias[] {
  return data.filter((entry) => entry.monster === monsterId);
}

export const cardNameAliases = data;
