// GENERATED by scripts/generate-element-table.ts -- do not edit by hand.
//
// Source: https://raw.githubusercontent.com/rathena/rathena/master/db/re/attr_fix.yml
// rAthena is GPL-3.0. These are the Renewal element modifiers, cited under the
// rule spec 3.10 draws: rAthena's FORMULA side is Renewal and may be
// referenced; its DATA side (monster stats, refine rates, skill trees) is
// reworked in Zero and may not.
//
// Percentages. 100 means unchanged, 0 means immune, negative means the hit
// heals the target. "Dark" in the source file is written "Shadow" here, the
// name the game and every other page on this site use.

export const ELEMENTS = ['Neutral', 'Water', 'Earth', 'Fire', 'Wind', 'Poison', 'Holy', 'Shadow', 'Ghost', 'Undead'] as const;

export type Element = (typeof ELEMENTS)[number];
export type ElementLevel = 1 | 2 | 3 | 4;

export const ELEMENT_TABLE: Record<ElementLevel, Record<Element, Record<Element, number>>> = {
  1: {
    Neutral: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 100, Holy: 100, Shadow: 100, Ghost: 90, Undead: 100 },
    Water: { Neutral: 100, Water: 25, Earth: 100, Fire: 150, Wind: 90, Poison: 150, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Earth: { Neutral: 100, Water: 100, Earth: 25, Fire: 90, Wind: 150, Poison: 150, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Fire: { Neutral: 100, Water: 90, Earth: 150, Fire: 25, Wind: 100, Poison: 150, Holy: 100, Shadow: 100, Ghost: 100, Undead: 125 },
    Wind: { Neutral: 100, Water: 150, Earth: 90, Fire: 100, Wind: 25, Poison: 150, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Poison: { Neutral: 100, Water: 150, Earth: 150, Fire: 150, Wind: 150, Poison: 0, Holy: 75, Shadow: 75, Ghost: 75, Undead: 75 },
    Holy: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 75, Holy: 0, Shadow: 125, Ghost: 100, Undead: 125 },
    Shadow: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 75, Holy: 125, Shadow: 0, Ghost: 100, Undead: 0 },
    Ghost: { Neutral: 90, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 75, Holy: 90, Shadow: 90, Ghost: 125, Undead: 100 },
    Undead: { Neutral: 100, Water: 100, Earth: 100, Fire: 90, Wind: 100, Poison: 75, Holy: 125, Shadow: 0, Ghost: 100, Undead: 0 },
  },
  2: {
    Neutral: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 100, Holy: 100, Shadow: 100, Ghost: 70, Undead: 100 },
    Water: { Neutral: 100, Water: 0, Earth: 100, Fire: 175, Wind: 80, Poison: 150, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Earth: { Neutral: 100, Water: 100, Earth: 0, Fire: 80, Wind: 175, Poison: 150, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Fire: { Neutral: 100, Water: 80, Earth: 175, Fire: 0, Wind: 100, Poison: 150, Holy: 100, Shadow: 100, Ghost: 100, Undead: 150 },
    Wind: { Neutral: 100, Water: 175, Earth: 80, Fire: 100, Wind: 0, Poison: 150, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Poison: { Neutral: 100, Water: 150, Earth: 150, Fire: 150, Wind: 150, Poison: 0, Holy: 75, Shadow: 75, Ghost: 75, Undead: 50 },
    Holy: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 75, Holy: 0, Shadow: 150, Ghost: 100, Undead: 150 },
    Shadow: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 75, Holy: 150, Shadow: 0, Ghost: 100, Undead: 0 },
    Ghost: { Neutral: 70, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 75, Holy: 80, Shadow: 80, Ghost: 150, Undead: 125 },
    Undead: { Neutral: 100, Water: 100, Earth: 100, Fire: 80, Wind: 100, Poison: 50, Holy: 150, Shadow: 0, Ghost: 125, Undead: 0 },
  },
  3: {
    Neutral: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 100, Holy: 100, Shadow: 100, Ghost: 50, Undead: 100 },
    Water: { Neutral: 100, Water: 0, Earth: 100, Fire: 200, Wind: 70, Poison: 125, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Earth: { Neutral: 100, Water: 100, Earth: 0, Fire: 70, Wind: 200, Poison: 125, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Fire: { Neutral: 100, Water: 70, Earth: 200, Fire: 0, Wind: 100, Poison: 125, Holy: 100, Shadow: 100, Ghost: 100, Undead: 175 },
    Wind: { Neutral: 100, Water: 200, Earth: 70, Fire: 100, Wind: 0, Poison: 125, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Poison: { Neutral: 100, Water: 125, Earth: 125, Fire: 125, Wind: 125, Poison: 0, Holy: 50, Shadow: 50, Ghost: 50, Undead: 25 },
    Holy: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 50, Holy: 0, Shadow: 175, Ghost: 100, Undead: 175 },
    Shadow: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 50, Holy: 175, Shadow: 0, Ghost: 100, Undead: 0 },
    Ghost: { Neutral: 50, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 50, Holy: 70, Shadow: 70, Ghost: 175, Undead: 150 },
    Undead: { Neutral: 100, Water: 100, Earth: 100, Fire: 70, Wind: 100, Poison: 25, Holy: 175, Shadow: 0, Ghost: 150, Undead: 0 },
  },
  4: {
    Neutral: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 100, Holy: 100, Shadow: 100, Ghost: 0, Undead: 100 },
    Water: { Neutral: 100, Water: 0, Earth: 100, Fire: 200, Wind: 60, Poison: 125, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Earth: { Neutral: 100, Water: 100, Earth: 0, Fire: 60, Wind: 200, Poison: 125, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Fire: { Neutral: 100, Water: 60, Earth: 200, Fire: 0, Wind: 100, Poison: 125, Holy: 100, Shadow: 100, Ghost: 100, Undead: 200 },
    Wind: { Neutral: 100, Water: 200, Earth: 60, Fire: 100, Wind: 0, Poison: 125, Holy: 100, Shadow: 100, Ghost: 100, Undead: 100 },
    Poison: { Neutral: 100, Water: 125, Earth: 125, Fire: 125, Wind: 125, Poison: 0, Holy: 50, Shadow: 50, Ghost: 50, Undead: 0 },
    Holy: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 50, Holy: 0, Shadow: 200, Ghost: 100, Undead: 200 },
    Shadow: { Neutral: 100, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 50, Holy: 200, Shadow: 0, Ghost: 100, Undead: 0 },
    Ghost: { Neutral: 0, Water: 100, Earth: 100, Fire: 100, Wind: 100, Poison: 50, Holy: 60, Shadow: 60, Ghost: 200, Undead: 175 },
    Undead: { Neutral: 100, Water: 100, Earth: 100, Fire: 60, Wind: 100, Poison: 0, Holy: 200, Shadow: 0, Ghost: 175, Undead: 0 },
  },
};

// Thai labels for the element names. The element names themselves stay English
// everywhere on this site, because the game prints them in English.
export const ELEMENT_LEVEL_LABEL = 'ระดับธาตุของเป้าหมาย';

export function elementModifier(
  attack: Element,
  defence: Element,
  defenceLevel: ElementLevel,
): number {
  return ELEMENT_TABLE[defenceLevel][attack][defence];
}
