// Generates lib/element-table.ts from the official Zero guide's tables.
//
// It used to read rAthena's attr_fix.yml, cited under spec 3.10's formula/data
// line. That was the best source available at the time and it is no longer the
// best one: the game's own guide publishes all four attribute levels, and 399
// of its 400 cells agree with rAthena, so the site now ships the official
// numbers and can drop the "unverified for Zero" warning the page carried.
//
// The one disagreement is documented in scripts/official-element-data.ts and
// kept as the official page has it.
//
// Run it with:  npx tsx scripts/generate-element-table.ts
// It writes lib/element-table.ts. Commit the output; this script exists so the
// values stay auditable, not so they are computed at build time.

import * as fs from 'fs';
import * as path from 'path';
import { OFFICIAL_COLUMNS, OFFICIAL_ELEMENT_TABLE } from './official-element-data';

const OUT = path.join(process.cwd(), 'lib', 'element-table.ts');

const ELEMENTS = [
  'Neutral',
  'Water',
  'Earth',
  'Fire',
  'Wind',
  'Poison',
  'Holy',
  'Shadow',
  'Ghost',
  'Undead',
] as const;

const LEVELS = [1, 2, 3, 4] as const;

function main(): void {
  // The official grid is defender-major; the site reads it attacker-major
  // ("I swing Fire, what happens?"), so it is transposed exactly once, here.
  const byAttacker: Record<number, Record<string, Record<string, number>>> = {};

  for (const level of LEVELS) {
    byAttacker[level] = {};
    for (const attacker of ELEMENTS) byAttacker[level][attacker] = {};

    for (const defender of ELEMENTS) {
      const row = OFFICIAL_ELEMENT_TABLE[level][defender];
      if (row.length !== OFFICIAL_COLUMNS.length) {
        throw new Error(`Lv${level} ${defender}: ${row.length} values, expected ${OFFICIAL_COLUMNS.length}`);
      }
      row.forEach((value, i) => {
        if (!Number.isInteger(value) || value < -100 || value > 200) {
          throw new Error(`Lv${level} ${OFFICIAL_COLUMNS[i]} -> ${defender}: ${value} is out of range`);
        }
        byAttacker[level][OFFICIAL_COLUMNS[i]][defender] = value;
      });
    }
  }

  // Refuses to write a partial file: a missing cell would render as a blank in
  // a table whose whole job is to be complete.
  for (const level of LEVELS) {
    for (const attacker of ELEMENTS) {
      for (const defender of ELEMENTS) {
        if (byAttacker[level][attacker][defender] === undefined) {
          throw new Error(`Lv${level} ${attacker} -> ${defender} is missing`);
        }
      }
    }
  }

  const rows = LEVELS.map((level) => {
    const body = ELEMENTS.map((attacker) => {
      const values = ELEMENTS.map((d) => `${d}: ${byAttacker[level][attacker][d]}`).join(', ');
      return `    ${attacker}: { ${values} },`;
    }).join('\n');
    return `  ${level}: {\n${body}\n  },`;
  }).join('\n');

  const file = `// GENERATED by scripts/generate-element-table.ts -- do not edit by hand.
//
// Source: Ragnarok Zero's own game guide, ระบบพิเศษ > ระบบธาตุ, transcribed in
// scripts/official-element-data.ts. These are the game's published numbers, not
// a Renewal reference -- 399 of the 400 cells match rAthena's Renewal table and
// the single difference is documented at the source.
//
// Percentages, read attacker-first: ELEMENT_TABLE[defenceLevel][attack][defence].
// 100 means unchanged, 0 means the hit does nothing, above 100 means stronger.
// The official page prints the Ghost column as "Ninja Aura"; the site uses
// Ghost, the name the monsters table and the game's element field use.

export const ELEMENTS = [${ELEMENTS.map((e) => `'${e}'`).join(', ')}] as const;

export type Element = (typeof ELEMENTS)[number];
export type ElementLevel = 1 | 2 | 3 | 4;

export const ELEMENT_TABLE: Record<ElementLevel, Record<Element, Record<Element, number>>> = {
${rows}
};

export const ELEMENT_LEVEL_LABEL = 'ระดับธาตุของเป้าหมาย';

export function elementModifier(
  attack: Element,
  defence: Element,
  defenceLevel: ElementLevel,
): number {
  return ELEMENT_TABLE[defenceLevel][attack][defence];
}
`;

  fs.writeFileSync(OUT, file, 'utf8');
  console.log(`wrote ${OUT}`);
  console.log(`${LEVELS.length} attribute levels x ${ELEMENTS.length} x ${ELEMENTS.length} = ${LEVELS.length * ELEMENTS.length ** 2} cells, from the official guide`);
}

main();
