// Generates lib/element-table.ts from the official Zero guide's tables.
//
// It used to read rAthena's attr_fix.yml, cited under spec 3.10's formula/data
// line. That was the best source available at the time and it is no longer the
// best one: the game's own guide publishes all four attribute levels, and 399
// of its 400 cells agree with rAthena, so the site now ships the official
// numbers and can drop the "unverified for Zero" warning the page carried.
//
// The one disagreement is documented in scripts/official-element-data.ts and
// overridden below, back to rAthena's value, on the site owner's judgement.
//
// Run it with:  npx tsx scripts/generate-element-table.ts
// It writes lib/element-table.ts. Commit the output; this script exists so the
// values stay auditable, not so they are computed at build time.

import * as fs from 'fs';
import * as path from 'path';
import { OFFICIAL_COLUMNS, OFFICIAL_ELEMENT_TABLE } from './official-element-data';

// Cells where the site deliberately ships something other than what the guide
// prints. Kept here rather than edited into official-element-data.ts so that
// file stays a faithful record of the page and the cross-check against rAthena
// keeps working.
//
// Undead -> Poison at level 2: the guide prints 75, rAthena says 50, and the
// guide's level-2 Poison row is character for character identical to its
// level-1 row -- the signature of a copy-paste slip. The site owner plays the
// game and judged it a typo on their page. rAthena's 75 / 50 / 25 / 0 series
// across the four levels is what ships.
const OVERRIDES: { level: 1 | 2 | 3 | 4; attack: string; defence: string; value: number; why: string }[] = [
  {
    level: 2,
    attack: 'Undead',
    defence: 'Poison',
    value: 50,
    why: 'guide prints 75; its level-2 Poison row duplicates level 1, and rAthena runs 75/50/25/0',
  },
];

const OUT = path.join(process.cwd(), 'lib', 'element-table.ts');

const ELEMENTS = [
  'Neutral',
  'Water',
  'Earth',
  'Fire',
  'Wind',
  'Poison',
  'Holy',
  'Shadow',
  'Ghost',
  'Undead',
] as const;

const LEVELS = [1, 2, 3, 4] as const;

function main(): void {
  // The official grid is defender-major; the site reads it attacker-major
  // ("I swing Fire, what happens?"), so it is transposed exactly once, here.
  const byAttacker: Record<number, Record<string, Record<string, number>>> = {};

  for (const level of LEVELS) {
    byAttacker[level] = {};
    for (const attacker of ELEMENTS) byAttacker[level][attacker] = {};

    for (const defender of ELEMENTS) {
      const row = OFFICIAL_ELEMENT_TABLE[level][defender];
      if (row.length !== OFFICIAL_COLUMNS.length) {
        throw new Error(`Lv${level} ${defender}: ${row.length} values, expected ${OFFICIAL_COLUMNS.length}`);
      }
      row.forEach((value, i) => {
        if (!Number.isInteger(value) || value < -100 || value > 200) {
          throw new Error(`Lv${level} ${OFFICIAL_COLUMNS[i]} -> ${defender}: ${value} is out of range`);
        }
        byAttacker[level][OFFICIAL_COLUMNS[i]][defender] = value;
      });
    }
  }

  for (const override of OVERRIDES) {
    const before = byAttacker[override.level][override.attack][override.defence];
    if (before === undefined) {
      throw new Error(`override targets a cell that does not exist: ${override.attack} -> ${override.defence}`);
    }
    if (before === override.value) {
      throw new Error(
        `override for Lv${override.level} ${override.attack} -> ${override.defence} is a no-op; the guide already says ${override.value}`,
      );
    }
    byAttacker[override.level][override.attack][override.defence] = override.value;
    console.log(
      `override Lv${override.level} ${override.attack} -> ${override.defence}: ${before} -> ${override.value} (${override.why})`,
    );
  }

  // Refuses to write a partial file: a missing cell would render as a blank in
  // a table whose whole job is to be complete.
  for (const level of LEVELS) {
    for (const attacker of ELEMENTS) {
      for (const defender of ELEMENTS) {
        if (byAttacker[level][attacker][defender] === undefined) {
          throw new Error(`Lv${level} ${attacker} -> ${defender} is missing`);
        }
      }
    }
  }

  const rows = LEVELS.map((level) => {
    const body = ELEMENTS.map((attacker) => {
      const values = ELEMENTS.map((d) => `${d}: ${byAttacker[level][attacker][d]}`).join(', ');
      return `    ${attacker}: { ${values} },`;
    }).join('\n');
    return `  ${level}: {\n${body}\n  },`;
  }).join('\n');

  const file = `// GENERATED by scripts/generate-element-table.ts -- do not edit by hand.
//
// Source: Ragnarok Zero's own game guide, ระบบพิเศษ > ระบบธาตุ, transcribed in
// scripts/official-element-data.ts. These are the game's published numbers, not
// a Renewal reference -- 399 of the 400 cells match rAthena's Renewal table.
// The single cell that differed, Lv2 Undead -> Poison, ships as rAthena has it
// (50, not the guide's 75): the guide's Lv2 Poison row duplicates its Lv1 row
// character for character, and the site owner, who plays the game, calls it a
// typo on their page. See OVERRIDES in the generator.
//
// Percentages, read attacker-first: ELEMENT_TABLE[defenceLevel][attack][defence].
// 100 means unchanged, 0 means the hit does nothing, above 100 means stronger.
// The official page prints the Ghost column as "Ninja Aura"; the site uses
// Ghost, the name the monsters table and the game's element field use.

export const ELEMENTS = [${ELEMENTS.map((e) => `'${e}'`).join(', ')}] as const;

export type Element = (typeof ELEMENTS)[number];
export type ElementLevel = 1 | 2 | 3 | 4;

export const ELEMENT_TABLE: Record<ElementLevel, Record<Element, Record<Element, number>>> = {
${rows}
};

export const ELEMENT_LEVEL_LABEL = 'ระดับธาตุของเป้าหมาย';

export function elementModifier(
  attack: Element,
  defence: Element,
  defenceLevel: ElementLevel,
): number {
  return ELEMENT_TABLE[defenceLevel][attack][defence];
}
`;

  fs.writeFileSync(OUT, file, 'utf8');
  console.log(`wrote ${OUT}`);
  console.log(`${LEVELS.length} attribute levels x ${ELEMENTS.length} x ${ELEMENTS.length} = ${LEVELS.length * ELEMENTS.length ** 2} cells, from the official guide`);
}

main();
